<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use Illuminate\Support\Collection;

class FiltersSheet implements FromCollection, WithHeadings, WithStyles, WithTitle
{
    protected $filters;
    protected $user;

    public function __construct($filters = [], $user = null)
    {
        $this->filters = $filters;
        $this->user = $user;
    }

    public function collection()
    {
        $data = collect([
            ['Filter', 'Value'],
            ['Generated By', $this->user ? $this->user->username : 'System'],
            ['User Role', $this->user ? $this->user->getRoleNames()->first() : 'Unknown'],
            ['Branch', $this->user ? $this->user->branch_name : 'All'],
            ['Generated At', now()->format('Y-m-d H:i:s')],
        ]);

        // Add filter information
        foreach ($this->filters as $key => $value) {
            if ($value) {
                $data->push([ucfirst(str_replace('_', ' ', $key)), $value]);
            }
        }

        return $data;
    }

    public function headings(): array
    {
        return [];
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => [
                'font' => ['bold' => true, 'size' => 12],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => '70AD47']
                ],
                'font' => ['color' => ['rgb' => 'FFFFFF']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]
            ]
        ];
    }

    public function title(): string
    {
        return 'Export Info';
    }
}
