<?php

namespace App\Exports;

use Illuminate\Support\Collection;

class SummaryReportExport
{
    protected $data;
    protected $filters;
    protected $user;

    public function __construct($data, $filters = [], $user = null)
    {
        $this->data = $data;
        $this->filters = $filters;
        $this->user = $user;
    }

    public function getData()
    {
        return [
            // Summary Sheet Data
            'summary' => [
                'headers' => ['Metric', 'Value', 'Description'],
                'data' => [
                    ['Total Pengajuan', $this->data['total_pengajuan'] ?? 0, 'Total number of requests'],
                    ['Total Disetujui', $this->data['total_disetujui'] ?? 0, 'Approved requests'],
                    ['Total Menunggu', $this->data['total_menunggu'] ?? 0, 'Pending requests'],
                    ['Total Ditolak', $this->data['total_ditolak'] ?? 0, 'Rejected requests'],
                    ['Total Selesai', $this->data['total_selesai'] ?? 0, 'Completed requests'],
                    ['Total Nilai (Rp)', number_format($this->data['total_nilai'] ?? 0, 0, ',', '.'), 'Total value in Rupiah'],
                ]
            ],
            // Export Info Sheet Data
            'info' => [
                'headers' => ['Property', 'Value'],
                'data' => [
                    ['Generated By', $this->user ? $this->user->username : 'System'],
                    ['User Role', $this->user ? $this->user->getRoleNames()->first() : 'Unknown'],
                    ['Branch', $this->user ? $this->user->branch_name : 'All'],
                    ['Generated At', now()->format('Y-m-d H:i:s')],
                ]
            ]
        ];
    }
}
