<?php

namespace App\Exports\Word;

use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;

class PengajuanReportWord
{
    protected array $reportData;
    protected array $filters;
    protected $user;

    public function __construct(array $reportData, array $filters, $user)
    {
        $this->reportData = $reportData;
        $this->filters = $filters;
        $this->user = $user;
    }

    public function generate(): string
    {
        $phpWord = new PhpWord();

        // Styles
        $phpWord->addFontStyle('title', ['bold' => true, 'size' => 16, 'color' => '2E74B5']);
        $phpWord->addFontStyle('heading', ['bold' => true, 'size' => 12]);
        $phpWord->addFontStyle('normal', ['size' => 10]);
        $phpWord->addTableStyle('reportTable', [
            'borderSize' => 6,
            'borderColor' => 'CCCCCC',
            'cellMargin' => 80,
        ]);

        $section = $phpWord->addSection(['marginTop' => 1000, 'marginBottom' => 1000]);

        // Header
        $section->addText('📝 LAPORAN PENGAJUAN', 'title');
        $section->addText('Generated: '.now()->format('d F Y, H:i'), 'normal');
        $section->addTextBreak(1);

        // Summary
        $summary = $this->reportData['summary'] ?? [];
        $section->addText('Ringkasan', 'heading');
        $sumTable = $section->addTable('reportTable');
        $sumTable->addRow();
        $sumTable->addCell(5000, ['bgColor' => '70AD47'])->addText('Metric', ['bold' => true, 'color' => 'FFFFFF']);
        $sumTable->addCell(3000, ['bgColor' => '70AD47'])->addText('Value', ['bold' => true, 'color' => 'FFFFFF']);

        $entries = [
            ['Total', $summary['total'] ?? ($this->reportData['details_count'] ?? 0)],
            ['Pending', $summary['pending'] ?? 0],
            ['Approved', $summary['approved'] ?? 0],
            ['Rejected', $summary['rejected'] ?? 0],
            ['Completed', $summary['completed'] ?? 0],
        ];
        foreach ($entries as $i => [$label, $val]) {
            $sumTable->addRow();
            $bg = $i % 2 === 0 ? 'F2F2F2' : 'FFFFFF';
            $sumTable->addCell(5000, ['bgColor' => $bg])->addText($label, 'normal');
            $sumTable->addCell(3000, ['bgColor' => $bg])->addText((string) $val, 'normal');
        }

        $section->addTextBreak(1);

        // Details
        $section->addText('Detail Pengajuan', 'heading');
        $table = $section->addTable('reportTable');
        $headers = ['ID', 'Pemohon', 'Status', 'Jumlah Item', 'Tanggal'];
        $table->addRow();
        foreach ($headers as $h) {
            $table->addCell(2000, ['bgColor' => '4472C4'])->addText($h, ['bold' => true, 'color' => 'FFFFFF', 'size' => 9]);
        }

        foreach (($this->reportData['details'] ?? []) as $i => $row) {
            $bg = $i % 2 === 0 ? 'F9F9F9' : 'FFFFFF';
            $table->addRow();
            $table->addCell(2000, ['bgColor' => $bg])->addText($row['id_pengajuan'] ?? '-', ['size' => 9]);
            $table->addCell(2000, ['bgColor' => $bg])->addText($row['pemohon'] ?? ($row['user']['username'] ?? '-'), ['size' => 9]);
            $table->addCell(2000, ['bgColor' => $bg])->addText($row['status_pengajuan'] ?? '-', ['size' => 9]);
            $table->addCell(2000, ['bgColor' => $bg])->addText((string)($row['jumlah_items'] ?? 0), ['size' => 9]);
            $table->addCell(2000, ['bgColor' => $bg])->addText(($row['created_at'] ?? '-'), ['size' => 9]);
        }

        $section->addTextBreak(1);
        $section->addText('Generated by SIPB System | '.now()->format('Y'), ['size' => 9, 'color' => '999999']);

        // Save temp file
        $fileName = $this->getFileName();
        $tempPath = storage_path('app/temp');
        if (!is_dir($tempPath)) { @mkdir($tempPath, 0777, true); }
        $filePath = $tempPath.'/'.$fileName;
        IOFactory::createWriter($phpWord, 'Word2007')->save($filePath);
        return $filePath;
    }

    public function getFileName(): string
    {
        return 'Pengajuan_Report_'.now()->format('Y-m-d_H-i-s').'.docx';
    }
}
